#!/usr/bin/env python3
"""Build plain single-file versions of each skill into dist/.

Use these in tools that do not load Agent Skills folders: paste one into a
rules file, project instructions or a system prompt.

    python scripts/build.py          # write dist/
    python scripts/build.py --check  # exit 1 if dist/ is out of date
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS_DIR = os.path.join(ROOT, "skills")
DIST = os.path.join(ROOT, "dist")


def read(path):
    with io.open(path, encoding="utf-8") as f:
        return f.read()


def split_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        raise ValueError("missing frontmatter")
    return m.group(1), m.group(2).lstrip("\n")


def skill_names():
    return sorted(
        d for d in os.listdir(SKILLS_DIR)
        if os.path.isfile(os.path.join(SKILLS_DIR, d, "SKILL.md"))
    )


def section(body, heading):
    m = re.search(r"^## " + re.escape(heading) + r"\n\n(.*?)(?=^## |\Z)", body, re.S | re.M)
    return m.group(1).strip() if m else ""


def build():
    out = {}
    checklist = [
        "<!-- Generated by scripts/build.py from skills/*/SKILL.md. Do not edit. -->",
        "",
        "# UX checklist",
        "",
        "The closing checks from every skill in this suite, for tools with a small instruction budget. "
        "Run the relevant sections before presenting a design or when reviewing one.",
        "",
    ]
    for name in skill_names():
        _, body = split_frontmatter(read(os.path.join(SKILLS_DIR, name, "SKILL.md")))
        header = "<!-- Generated by scripts/build.py from skills/%s/SKILL.md. Do not edit. -->\n\n" % name
        out["%s.md" % name] = header + body.rstrip() + "\n"
        check = section(body, "Closing check")
        if check:
            title = re.search(r"^# (.+)$", body, re.M).group(1)
            checklist += ["## " + title, "", check, ""]
    out["ux-checklist.md"] = "\n".join(checklist).rstrip() + "\n"
    return out


def main(argv):
    files = build()
    if "--check" in argv:
        stale = []
        for fn, content in files.items():
            p = os.path.join(DIST, fn)
            if not os.path.isfile(p) or read(p) != content:
                stale.append(fn)
        extra = [f for f in os.listdir(DIST) if f not in files] if os.path.isdir(DIST) else []
        if stale or extra:
            print("dist/ is out of date. Run: python scripts/build.py")
            for f in stale:
                print("  stale: " + f)
            for f in extra:
                print("  unexpected: " + f)
            return 1
        print("dist/ is up to date")
        return 0
    os.makedirs(DIST, exist_ok=True)
    for fn, content in files.items():
        with io.open(os.path.join(DIST, fn), "w", encoding="utf-8") as f:
            f.write(content)
        print("wrote dist/" + fn)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
